### ISSUE TITLE
Latest changes have broken home assistant

### ISSUE THREAD

**Issue by swails** [gurumitts/pylutron-caseta#60] opened 2020-10-31 04:20 UTC
See home-assistant/core#42653 - I can reproduce the problem (HA can receive and update light statuses but can't send any commands to the Lutron Smart Bridge).

I think it boils down to the client tag not being used correctly in this library.  The intent behind the client tag is that each client uses the same tag for every single request.  We should pick something like `PYLUTRON_CASETA` or something recognizable rather than a random GUID each time.  It also means we can't use the client tag in order to recognize responses to specific requests.

Fun fact, some Lutron devices (like connect bridges) actually have a maximum number of distinct clients that can connect due to the nature of the legacy hardware that it interacts with (HWQS Proc and RRA2 Main Repeater), and after a fairly small number of messages actually starts rejecting everything.

**Comment by swails** [comment] 2020-10-31 04:33
This is going to require a fairly hefty refactor given that the client tag is being used to pair requests and responses in a way that was never intended by the Lutron bridge, so I don't really have time to tackle it.  The response is supposed to be paired to the request by matching the ReadResponse to the ReadRequest on the same href with the same client tag.  If the same client sends two requests really quickly, you can't be sure which response was triggered by which request.

**Comment by mdonoughe** [comment] 2020-10-31 16:47
Are you sure? I have been using this version for weeks and I have restarted Home Assistant many times because I have been testing other things without encountering any startup issues.

In general, the client tag pattern usually allows the client to pass any arbitrary data so that it can associate returned response messages with the client-side operations. At least last I checked, the Android app works the same way, and sends many different client tag values.

If the user were having the problem you describe where sending multiple simultaneous requests causes the bridge to send multiple responses with the same client tag, the user would be receiving "Was not expecting message with tag" errors in the log.

Also, in any case it does not make sense that it would hang this way. Smartbridge implements a five second timeout for every request to the bridge, including the setup requests, so it should not be possible for setup to hang in this way.

More likely, this has always been broken, just not in a way the user noticed. IIRC in the old version, certain requests sent during initialization did not receive a response. It should be possible to tell by enabling debug mode and analyzing the messages sent and received, but also it might be possible to tell by simply disconnecting the bridge from the network, waiting for the connection timeout to occur, and checking the logged stacks for BridgeDisconnectedException.

It wouldn't be too much of a refactor to always use the same tag and only submit one request at a time, but I don't think it will help, and it could have a noticeable performance impact. The older code also sent unlimited simultaneous requests and did not track how many where in progress. If you want to for testing, in `LeapProtocol.request`, replace `tag = str(uuid.uuid4())` with something constant, and put an asyncio.Lock around the `self._writer.write(text + b"\r\n") and `return await future`. This leaves all the other code in place for now, but limits the client to one request at a time and using a stable tag value.

**Comment by chrisaljoudi** [comment] 2020-10-31 18:40
Probably related to home-assistant/core#42620

**Comment by mdonoughe** [comment] 2020-10-31 21:25
@chrisaljoudi Do you have occupancy sensors and they aren't working, but everything else is?

**Comment by chrisaljoudi** [comment] 2020-10-31 22:10
@mdonoughe yep. I suspect the issue is that `_request` is used for subscribing to occupancy sensor events (which get the client tag returned and are not ‘unsolicited’), and `_request` only expects one “response” for any message it writes (obviously untrue of a subscription 😊).

See [this](https://github.com/gurumitts/pylutron-caseta/blob/db55187f620d7957da4f2e264d3e9f47a9c3c0f5/pylutron_caseta/leap.py#L46) where each future is setup to expect exactly one response.

Also see [this](https://github.com/gurumitts/pylutron-caseta/blob/db55187f620d7957da4f2e264d3e9f47a9c3c0f5/pylutron_caseta/leap.py#L76) where the presence of a tag (in this case one we currently include in the subscription request) makes those occupancy status events neither unsolicited nor “expected” (and are thus dropped with the unexpected tag error we’re seeing).

**Comment by mdonoughe** [comment] 2020-10-31 23:30
Before 0.7, all messages were unsolicited. In pylutron_caseta 0.7.0 expects that the occupancy group updates will not be tagged, the same as the light updates. That's not right.

**Comment by swails** [comment] 2020-11-01 00:00
This isn't the updates, it's the subscribe request to send occupancy group updates. That looks like the problem. 

It should probably only look for responses to ReadRequest messages (don't go strictly by client tag).

**Comment by mdonoughe** [comment] 2020-11-01 17:47
@swails do you still think there will be problems? I think all the reported issues have been fixed by 0.7.1 and I haven't been noticing stability issues running this code for longer, but I "only" have 12 lights, 1 switch, and one "ceiling fan" (it's just a ceiling fan switch in a single gang electrical box).

It would probably be possible to correlate requests through other means to have less reliance on tags, but if client tags are supposed to work as you say (ie each client always uses the same tag) we could not use a "PYLUTRON_CASETA" tag because the only logical purpose of having such a tag at that point, since the client has already identified itself to the bridge by using its TLS client certificate, would be if responses were broadcast to all clients and the client needed to filter out messages from other clients. In that case, using "PYLUTRON_CASETA" would cause problems if two instances of pylutron_caseta were used to connect to the same bridge at the same time.

In the Android app, at least sometimes, ClientTag is generated by concatenating a client device ID and an incrementing number, so it should be safe to use a different ClientTag value on every request unless the bridge is parsing the ClientTag (possible, but bad software design). Additionally, the client ID may actually be a random UUID generated at app installation, in which case the tags generated by the app could be larger than the tags generated by pylutron_caseta, so there shouldn't be any issues with the size of the tags.

**Comment by swails** [comment] 2020-11-02 05:09
If the android app is using unique client tags then it's probably fine. 

The only system I knew was sensitive to client tags was the connect bridge, which provides some caseta functionality to the legacy RA2 and HWQS systems. But that was because of the proc it connected to, not the bridge itself. I was never fully clear on how that tag was meant to be used, so I just adopted the one-tag-per-client rule needed for connect bridges. 

I can try 0.7.1 with my system to see if it fixes the issue (I also have occ sensors, which is why it didn't work for me before).

**Comment by gmcmicken** [comment] 2020-11-02 19:20
I've just added an occupancy sensor to my setup and it stops reporting, or home assistant stops receiving, status updates. I can still control lights after the sensor stops working. Restarting home assistant fixes it for a while. Can I provide any assistance?

**Comment by mdonoughe** [comment] 2020-11-03 03:00
Do you get anything in the logs? Do the sensor changes still show up in the Android app?

**Comment by gmcmicken** [comment] 2020-11-04 20:41
I'm on home assistant 117.2, and my logs show when it breaks with the following:

```
LEAP session ended. Reconnecting...
8:35:17 AM – /home/ha/Downloads/homeassistant/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py (WARNING) - message first occurred at November 3, 2020, 2:10:09 PM and shows up 6 times
```

```
ping was not answered. closing connection.
8:35:15 AM – /home/ha/Downloads/homeassistant/lib/python3.7/site-packages/pylutron_caseta/smartbridge.py (WARNING) - message first occurred at November 3, 2020, 2:10:08 PM and shows up 6 times
```

Let me know if there's additional logging I can/should turn on. The sensor changes show up in the lutron app after they stop showing in home assistant.

**Comment by gmcmicken** [comment] 2020-11-04 21:59
What's interesting is that the status updates from the occupancy sensor stop at the first occurrence of this message, but the bridge must be successfully reconnected thereafter because light commands continue to work and light statuses continue to be updated - so it seems the monitor of occupancy events is not being restarted after the connection is lost and re-established.

**Comment by mdonoughe** [comment] 2020-11-05 01:00
That is an interesting theory, but I think the problem is more complicated. `Smartbridge._monitor_once` is called every time a connection is established to the Caséta bridge, and that spins off a task which subscribes to the occupancy group status, and the subscription from Home Assistant does not get cleared, so it is still there and should still be getting called.

However, `Smartbridge._process_occupancy_group` replaces all the values in `self.occupancy_groups` every time it is run. This sounds similar to a problem Home Assistant had before, where it was taking a reference to a dictionary owned by pylutron_caseta, subscribing to the change events and looking at the dictionary it picked up originally, but somewhere in between pylutron_caseta had replaced that dictionary with a different one. Sure enough, in the Home Assistant code I can see the integration is doing the same thing in this case.

I don't think this is a new bug in 0.7 or Home Assistant 0.117. From the code history it looks like the problem has been there since support for occupancy groups was originally added. I don't know if nobody complained earlier because they don't use occupancy groups, because they just restart Home Assistant when it breaks, or because their bridges don't get disconnected often enough for them to notice.

I'll fix it the same way as last time this kind of bug happened. `_process_occupancy_group` should merge the updated status with the existing status.

**Comment by mdonoughe** [comment] 2020-11-05 01:35
Can you try the code change in #65? I usually copy the lutron_caseta integration from Home Assistant into my custom_integrations folder and change the manifest to reference the Git repo (eg https://github.com/mdonoughe/home-assistant/commit/a51dc2f8add6ddb14dabf206ad1979d188626b91) and then Home Assistant downloads the updated code into deps on startup.

**Comment by gmcmicken** [comment] 2020-11-05 04:18
Sure I'll test it out now leave it running, as soon as I see a LEAP session ended / ping timeout in the log I'll try triggering the occupancy sensor and check the status in HA. 

Entirely possible this existed for some time but most people have their HA hardwired and/or more stable connection than I do, and therefore do not see the issue as frequently. I myself cannot go a whole day without it breaking though!

**Comment by mdonoughe** [comment] 2020-11-08 16:28
Has Home Assistant been working better with the updated pylutron_caseta?

**Comment by gmcmicken** [comment] 2020-11-09 20:25
Isn't it always the case, I made the code change to test but there hasn't been any disconnects occurred to know for sure. I guess I could pull the ethernet to the bridge for a moment?

**Comment by gmcmicken** [comment] 2020-11-09 20:31
Okay, pulled the ethernet got the log message disconnected and reconnecting, plugged it back in and triggered the occupancy sensor - state change showed up in HA. All is good thanks for your help @mdonoughe

**Closed** 2020-11-19 04:27 UTC
